### PR TITLE
Add integration test for FastTransforms

### PR DESCRIPTION
**Pull request by gaurav-arya**

### CODE REVIEW

**Comment by gaurav-arya** [comment]
@devmotion this is ready for review. I had to hackily fix FFTW at v1.5 for the FastTransforms.jl test to account for https://github.com/JuliaApproximation/FastTransforms.jl/pull/192 / https://github.com/JuliaApproximation/FastTransforms.jl/pull/193, but I'll remove it ASAP once those are sorted out.

**Comment by devmotion** [comment]
Hmm this workaround is annoying and I'm worried we'll forget to remove it. We could merge and open an issue in AbstractFFTs about removing it, but given that the iaaue was only reported yesterday and the PR is not completely urgent, maybe it's easier to just wait until it is fixed in FastTransforms?

**Comment by gaurav-arya** [comment]
I'm fine with that as long as this doesn't block #84 -- shall we satisfy ourselves with local tests there for now?

**Comment by gaurav-arya** [comment]
Looks ready for mergeg

**Pull request merged**
