### PR TITLE
Ensure all fft-like functions fallback to version with region when region not provided

### PR DESCRIPTION
**Pull request by gaurav-arya**

### CODE REVIEW

**Comment by gaurav-arya** [comment]
@devmotion regarding documentation, the README already asks that downstream implementations only define `AbstractFFTs.plan_fft(x, region)`, so I'm not sure if anything more is necessary?

**Review by devmotion — COMMENTED** [review]
The code looks good to me. However, could we check that it does not break downstream packages? It seems we only test FFTW but IIRC there are other implementations of AbstractFFTs as well (might be good to add them to the integration tests?).

It seems in the documentation (e.g., https://juliamath.github.io/AbstractFFTs.jl/dev/) it is not mentioned that one should implement methods with `region`.

**Comment by gaurav-arya** [comment]
The instructions for defining a new implementation [here](https://juliamath.github.io/AbstractFFTs.jl/dev/implementations/#FFT-Implementations) completely omit how the plan should be formed, only what it should do. I think only the README discusses it. So the documentation could definitely be improved but it's out of scope for this PR?

Regarding integration tests, I think [CUDA](https://github.com/JuliaGPU/CUDA.jl/tree/master/lib/cufft) and [AMD]() define GPU FFTs, and [FastTransforms](https://github.com/JuliaApproximation/FastTransforms.jl/blob/master/src/nufft.jl) and [PencilFFTs](https://github.com/jipolanco/PencilFFTs.jl/blob/master/src/plans.jl) both subtype `AbstractFFTs.Plan` and possibly rely on some other functionality. What do you think needs an integration test, and are GPUs an issue for tests?

**Comment by gaurav-arya** [comment]
I ran the test suite for FastTransforms locally and that one is fine. Unfortunately I don't have a GPU setup for testing CUDA/AMD.

**Comment by gaurav-arya** [comment]
Regarding the CUDA implementation: Yeah, there seems to be a fair bit of code duplication in that file. I don't know, however, how much of it is simply redundant code and how much of it could be necessary hacks by downstream implementations to get past the various unresolved issues made in this repo. I'm tempted to keep the focus solely on the goal of supporting chain rules for now. I would like to work on refactoring to make sure AbstractFFTs makes life easy for downstream implementations in the future (starting with https://github.com/JuliaMath/AbstractFFTs.jl/issues/32...), but for now I'm content with making sure nothing breaks.

**Comment by devmotion** [comment]
Yes, sure, improving CUDA is beyond the scope of this PR. The copied code only made me wonder whether this PR might break CUDA. Could we add FastTransforms to the integration tests? I'll try to test CUDA, I should have access to some GPUs.

**Comment by devmotion** [comment]
I ran the test/cufft.jl tests in CUDA with this PR, they passed successfully:
```julia
julia> include("cufft.jl")
Test Summary:  | Pass  Total   Time
T = ComplexF32 |   49     49  10.3s
Test Summary:  | Pass  Total  Time
T = ComplexF64 |   49     49  6.9s
Test Summary: | Pass  Total  Time
T = Float32   |   34     34  5.3s
Test Summary: | Pass  Total  Time
T = Float64   |   34     34  5.1s
Test Summary:      | Pass  Total  Time
T = Complex{Int32} |    2      2  8.4s
Test Summary:      | Pass  Total  Time
T = Complex{Int64} |    2      2  1.2s
Test Summary: | Pass  Total  Time
T = Int32     |    2      2  2.4s
Test Summary: | Pass  Total  Time
T = Int64     |    2      2  1.2s
Test Summary: | Pass  Total  Time
CUDA.jl#1268  |    1      1  6.6s
Test Summary: | Pass  Total  Time
CUDA.jl#1311  |    1      1  0.1s
Test.DefaultTestSet("CUDA.jl#1311", Any[], 1, false, false, true, 1.678232934992004e9, 1.678232935079531e9)

(jl_MyiIuu) pkg> st
Status `/tmp/jl_MyiIuu/Project.toml`
  [621f4979] AbstractFFTs v1.2.1 `../../home/davwi492/sources/AbstractFFTs.jl`
  [79e6a3ab] Adapt v3.6.1
  [ab4f0b2a] BFloat16s v0.4.2
  [052768ef] CUDA v4.0.1
  [7a1cc6ca] FFTW v1.6.0
  [0c68f7d7] GPUArrays v8.6.3
```

**Comment by gaurav-arya** [comment]
> Could we add FastTransforms to the integration tests?

#86

**Review by devmotion — APPROVED** [review]
LGTM, local tests indicate it does not break downstream packages. I don't think we have to wait for #86.

**Comment by trahflow** [comment]
Would you mind also doing a release?
I would then go ahead and [drop the custom adjoints in Zygote](https://github.com/FluxML/Zygote.jl/pull/1386)

**Comment by gaurav-arya** [comment]
1.0 tests seem to have failed, maybe due to the ChainRulesCore weak dependency?? Will take a look asap

**Comment by gaurav-arya** [comment]
I see, thanks

**Comment by vpuri3** [comment]
@gaurav-arya maybe we need something similar in FFTW for DCTs.

**Pull request merged**
